//
// Created by apenchev on 6/2/2022.
//

#ifndef SVG_PARSER_DOMERRORCODE_H
#define SVG_PARSER_DOMERRORCODE_H

enum DomErrorCode {
    CANNOT_SET_NULLPTR_AS_DOM_VALUE,
    INVALID_DOM_ELEMENT_FORMAT,
    INVALID_DOM_ATTRIBUTE_FORMAT,
};

#endif //SVG_PARSER_DOMERRORCODE_H
