//
// Created by apenchev on 5/30/2022.
//

#ifndef SVG_PARSER_HELPERERRORCODE_H
#define SVG_PARSER_HELPERERRORCODE_H

enum HelperErrorCode {
    CANNOT_SET_NULLPTR_AS_HELPER_VALUE,
    INDEX_OUT_OF_INDEX
};

#endif //SVG_PARSER_HELPERERRORCODE_H
